# -*- coding: utf-8 -*-
"""atv-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ghz9MqD6l-vvQyRnqduUknzvLAHubbqB
"""

lista_estoque1 = []

produto1 = {
    "nome": "nescau",
    "preco": 15,
    "quantidade": 400
}

lista_estoque1.append(produto1)

produto2 = {
    "nome": "leite condensado",
    "preco": 12,
    "quantidade": 620
}

lista_estoque1.append(produto2)

produto3 = {
    "nome": "leite 2l",
    "preco": 6,
    "quantidade": 200
}

lista_estoque1.append(produto3)

for produto in lista_estoque1:
  prod = produto["nome"]
  prec = produto["preco"]
  qnt = produto["quantidade"]

  print(f"{prod}, custa R${prec} e temos {qnt}")

lista_votos = {
    "Cleber": 7,
    "Bruno": 14,
    "Tercio": 21,
    "Orrico": 28,
    "Felfoldi": 35,
    "Roger": 42
}

def contar_voto():
  candidato = str(input("Em qual candidato você deseja votar? "))
  if candidato in lista_votos:
    lista_votos[candidato] += 1
  else:
    lista_votos[candidato] = 1

contar_voto()
for candidato, votos in lista_votos.items():
  print(f"{candidato}: {votos} votos")

print(lista_votos)